version: '3.8'

services:
  smartvoc-api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: smartvoc-api
    restart: unless-stopped
    ports:
      - "8000:5000"
    volumes:
      - .:/app
      - smartvoc_data:/app/instance
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      # Variables para la base de datos SQLite (desarrollo)
      - DATABASE_URL=sqlite:///instance/smartvoc.db
      # Variables para SQL Server (descomentar cuando sea necesario)
      # - DATABASE_URL=mssql+pyodbc://username:password@server:1433/database?driver=ODBC+Driver+17+for+SQL+Server
      # - DB_SMARTVOC_URI=mssql+pyodbc://smartvoc:password@smartvoc.database.windows.net:1433/SmartVOC?driver=ODBC+Driver+17+for+SQL+Server
    command: >
      bash -c "mkdir -p /app/instance &&
               chmod 777 /app/instance &&
               python -m flask run --host=0.0.0.0 --port=5000"
    networks:
      - smartvoc-network

# Volumen para persistir la base de datos y otros datos
volumes:
  smartvoc_data:

networks:
  smartvoc-network:
    driver: bridge 