version: '3.8'

services:
  smartvoc-api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: smartvoc-api
    restart: unless-stopped
    ports:
      - "8000:5000"
    volumes:
      - .:/app
      - smartvoc_data:/app/instance
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: >
      bash -c "mkdir -p /app/instance &&
               chmod 777 /app/instance &&
               python -m flask run --host=0.0.0.0 --port=5000"
    networks:
      - smartvoc-network

# Volumen para persistir la base de datos y otros datos
volumes:
  smartvoc_data:

networks:
  smartvoc-network:
    driver: bridge 